### ISSUE TITLE
IsAuthenticated() always returns "true" when using "/login" route 

### ISSUE THREAD

**Issue by sshikaree** [martini-contrib/sessionauth#12]
There is a problem when I try to handle "/login". `user.IsAuthenticated()` always returns `true`, when opening this route. Here is example - https://gist.github.com/sshikaree/9d60b88d261dfb20f449

**Comment by rday** [comment]
I'm not able to reproduce the "true" error. When using your code I get "User is logged in: false" for both /login and /anythingelse.

Are you able to print out the entire object? It seems that nothing is being modified, so the 0'd User interface should still have 0 in the logged_in part.

Right now the code is also skipping the sessionauth package, with the exception of the User interface. You would normally want to chain the sessionauth.LoginRequired method to force a login.

**Comment by sshikaree** [comment]
Thanks for reply!
I apologize for inattention, I had to clear the browser cache.

**Comment by rday** [comment]
No problems at all! Browser cache is trying to destroy me as well :)
