### ISSUE TITLE
Is Id field required for User struct?

### ISSUE THREAD

**Issue by ovidiuvisan** [martini-contrib/sessionauth#15]
Hi, can i use the User struct without an Id field? Included below is the User struc i used, with the UniqueId and GetById functions and also the error. I don't need an Id, because the email is the id for what i need.
Thanks.

type User struct {
    Email           string `form:"email" db:"stremail" binding:"required"`
    Name            string `form:"name" db:"strname"`
    Password        string `form:"password" db:"strpassword" binding:"required"`
    ConfirmPassword string
    authenticated   bool `form:"-" db:"-"`
}

func (u *User) UniqueId() interface{} {
    return u.Email
}
func (u *User) GetById(id interface{}) error {
    err := dbmap.SelectOne(u, "SELECT \* FROM tblcustomer WHERE stremail = ?", id)
    if err != nil {
        return err
    }
    return nil
}

[martini] PANIC: runtime error: invalid memory address or nil pointer dereference
/home/ovidiu/go/src/pkg/runtime/panic.c:482 (0x4174bd)
    panicstring: runtime·panic(err);
/home/ovidiu/go/src/pkg/runtime/os_linux.c:234 (0x41635a)
    sigpanic: runtime·panicstring("invalid memory address or nil pointer dereference");
/home/ovidiu/go/external/src/github.com/coopernurse/gorp/gorp.go:1085 (0x46076e)
    (_DbMap).trace: if m.logger != nil {
/home/ovidiu/go/external/src/github.com/coopernurse/gorp/gorp.go:1080 (0x4606de)
    (_DbMap).query: m.trace(query, args...)
/home/ovidiu/go/external/src/github.com/coopernurse/gorp/gorp.go:1347 (0x4629e2)
    selectVal: rows, err := e.query(query, args...)
/home/ovidiu/go/external/src/github.com/coopernurse/gorp/gorp.go:1335 (0x462747)
    SelectOne: return selectVal(e, holder, query, args...)
/home/ovidiu/go/external/src/github.com/coopernurse/gorp/gorp.go:1019 (0x45fc94)
    (_DbMap).SelectOne: return SelectOne(m, m, holder, query, args...)
/home/ovidiu/go/external/src/github.com/martini-contrib/sessionauth/sessionauth.go:62 (0x4782f5)
    func.001: err := user.GetById(userId)
/home/ovidiu/go/src/pkg/runtime/asm_amd64.s:340 (0x427792)
    call64: CALLFN(call64, 64)
/home/ovidiu/go/src/pkg/reflect/value.go:474 (0x4e4aab)
    Value.call: call(fn, ptr, uint32(size))
/home/ovidiu/go/src/pkg/reflect/value.go:345 (0x4e3b9d)
    Value.Call: return v.call("Call", in)
/home/ovidiu/go/external/src/github.com/codegangsta/inject/inject.go:102 (0x56dd24)
    (_injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/ovidiu/go/external/src/github.com/go-martini/martini/martini.go:165 (0x469882)
    (_context).run: _, err := c.Invoke(c.handler())
/home/ovidiu/go/external/src/github.com/go-martini/martini/martini.go:156 (0x4697db)
    (_context).Next: c.run()
/home/ovidiu/go/external/src/github.com/martini-contrib/sessions/sessions.go:95 (0x478ec4)
    func.002: c.Next()
/home/ovidiu/go/src/pkg/runtime/asm_amd64.s:340 (0x427792)
    call64: CALLFN(call64, 64)
/home/ovidiu/go/src/pkg/reflect/value.go:474 (0x4e4aab)
    Value.call: call(fn, ptr, uint32(size))
/home/ovidiu/go/src/pkg/reflect/value.go:345 (0x4e3b9d)
    Value.Call: return v.call("Call", in)
/home/ovidiu/go/external/src/github.com/codegangsta/inject/inject.go:102 (0x56dd24)
    (_injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/ovidiu/go/external/src/github.com/go-martini/martini/martini.go:165 (0x469882)
    (_context).run: _, err := c.Invoke(c.handler())
/home/ovidiu/go/external/src/github.com/go-martini/martini/martini.go:156 (0x4697db)
    (_context).Next: c.run()
/home/ovidiu/go/external/src/github.com/go-martini/martini/recovery.go:140 (0x46dbc6)
    func.004: c.Next()
/home/ovidiu/go/src/pkg/runtime/asm_amd64.s:339 (0x427732)
    call32: CALLFN(call32, 32)
/home/ovidiu/go/src/pkg/reflect/value.go:474 (0x4e4aab)
    Value.call: call(fn, ptr, uint32(size))
/home/ovidiu/go/src/pkg/reflect/value.go:345 (0x4e3b9d)
    Value.Call: return v.call("Call", in)
/home/ovidiu/go/external/src/github.com/codegangsta/inject/inject.go:102 (0x56dd24)
    (_injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/ovidiu/go/external/src/github.com/go-martini/martini/martini.go:165 (0x469882)
    (_context).run: _, err := c.Invoke(c.handler())
/home/ovidiu/go/external/src/github.com/go-martini/martini/martini.go:156 (0x4697db)
    (_context).Next: c.run()
/home/ovidiu/go/external/src/github.com/go-martini/martini/logger.go:25 (0x46d4d2)
    func.001: c.Next()
/home/ovidiu/go/src/pkg/runtime/asm_amd64.s:340 (0x427792)
    call64: CALLFN(call64, 64)
/home/ovidiu/go/src/pkg/reflect/value.go:474 (0x4e4aab)
    Value.call: call(fn, ptr, uint32(size))
/home/ovidiu/go/src/pkg/reflect/value.go:345 (0x4e3b9d)
    Value.Call: return v.call("Call", in)
/home/ovidiu/go/external/src/github.com/codegangsta/inject/inject.go:102 (0x56dd24)
    (_injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/ovidiu/go/external/src/github.com/go-martini/martini/martini.go:165 (0x469882)
    (_context).run: _, err := c.Invoke(c.handler())
/home/ovidiu/go/external/src/github.com/go-martini/martini/martini.go:69 (0x468b83)
    (_Martini).ServeHTTP: m.createContext(res, req).run()
/home/ovidiu/go/src/pkg/net/http/server.go:1597 (0x48c84e)
    serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/home/ovidiu/go/src/pkg/net/http/server.go:1167 (0x48a7f7)
    (_conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/home/ovidiu/go/src/pkg/runtime/proc.c:1394 (0x41af20)
    goexit: runtime·goexit(void)
[martini] Completed 500 Internal Server Error in 12.121654ms

**Comment by rday** [comment]
Hi Ovidiu!

What does your user db table look like? You may need to set db:"-" on the
ConfirmPassword field.

**Comment by ovidiuvisan** [comment]
Hi Ryan!
i use a different struct in my DB for the user table, here it is (the table is created with gorp):
type Customer struct {
    StrName     string  `db:"strname"`
    StrEmail    string  `db:"stremail"`
    StrPassword string  `db:"strpassword"`
    SglBalance  float32 `db:"sglbalance"`
}
The DB is handled in a separate package which i created, so it was difficult to make the customer table struct to implement the methods required by sessionauth, so i created a separated struct for the login called User.
Also i have added  `db:"-"` to the ConfirmPassword, but there is the same problem.
What can i do?

**Comment by ovidiuvisan** [comment]
Found the culprit...it was my mistake, sorry man. Great job with this package!

**Comment by rday** [comment]
Thanks! Disappeared for a bit, but glad it worked out for you.
