### ISSUE TITLE
Login function called for each request

### ISSUE THREAD

**Issue by ventayol** [martini-contrib/sessionauth#18]
Why the Login function is called for each request?
I think the user should be kept in the session and Login function should be called once.

**Comment by rday** [comment]
The user.IsAuthenticated function could check the current session I
suppose. I have always tried to stay away from keeping too much data
encrypted inside the actual cookie in fear of leaking key information. So I
generally keep very small amounts in a cookie and sign the cookie. Or check
some header on each request and determine request state on a per-request
basis.
