### ISSUE TITLE
Remember Me functionality

### ISSUE THREAD

**Issue by leebrooks0** [martini-contrib/sessionauth#8]
First of all, thanks for creating this plugin :) !

Right now the authenticated user is logged on for the life of the session, personally I am using 30 days for the session duration. 

If the user is at an internet cafe for example they might not want to be logged in once they have left. I am not quite sure on how to do this.

Perhaps adding a variable to this plugin RememberMeFor as duration eg. 30 mins, on login stamp the session with  the initial LastActiveAt, and then in the LoginRequiredHandler if (Time.Now() - LastActiveAt) is greater than RememberMeFor, then log the user out, else update LastActiveAt and proceed.

What do you think?

**Comment by rday** [comment]
I'm glad you like it!

Great catch on this session expiration. I think this is actually best
solved in the session -contrib. We should be able to create a Session with
a MaxAge of 0, which _should_ expire the cookie when the browser is closed.
That really should be the default and is really a vulnerability as it
stands.

Remember Me should be something the user has to manual choose to do.

I've got to finish up something this morning, but I wanted to get back to
you. I'll be able to look at this in the afternoon.

**Comment by rday** [comment]
Alright, so Jeremy bet me to it.

http://www.reddit.com/r/golang/comments/1yh6gm/new_to_go_trying_to_select_web_framework/cfkjnin

I'm going to move this over to session-contrib though. I'd wonder if the defaults should be session cookies.
